4-1 DDL確認依頼
Itopan1108/webapp1-countup-Renew- pull request #10
Opened 2023-10-09 00:45 UTC by Itopan1108

@esmtodoroki
@h-yokoyama-eiwa
@ma-miyagawa

４－１　テーブル作成のためのＤＤＬの確認依頼です。
OK後、DB作成を行いますので、よろしくお願いします。

（社内のVPN接続は正常に完了しました。ちなみに、今は福井にいます。）

2023-10-09 04:37 UTC, h-yokoyama-eiwa requested changes
@Itopan1108 
コメントしました。

2023-10-09 04:37 UTC, h-yokoyama-eiwa commented on DDLcreate.txt
> +);
非常にシンプルですね。
ちょっと古い記事ですが、こちらを参考に見直してみてください。
特にテーブル名と必須カラムを。
https://qiita.com/genzouw/items/35022fa96c120e67c637

2023-10-09 05:54 UTC, ma-miyagawa commented on DDLcreate.txt
> +);
主キー(例 id)を項目に追加してください。
https://uxmilk.jp/12787

※後続のタスクで、キーのデータがあるときはupdate、ないときはinsertのSQLを実行するとき
主キーがないといけないためです。あとでテーブルを修正するのは面倒だと思うのでこれを機会に対応したほうが
良いです。

2023-10-09 05:55 UTC, ma-miyagawa commented
@Itopan1108 

コメントしました。

2023-10-10 07:21 UTC, esmtodoroki commented on DDLcreate.txt
> +);
今回の課題では主キーを設定しなくても稼働できると思います。
自分も主キー用の項目を作成しましたが、結果的に使うことはありませんでした。
が、テーブルを作成するお作法としてキー項目を持たせたほうが良いと思うので、
結果的に使わなくても、キー項目を作る練習をしておきましょう。

2023-10-10 07:22 UTC, esmtodoroki commented
@Itopan1108 
コメントしました

2023-10-10 12:43 UTC, Itopan1108 commented on DDLcreate.txt
> +);
@ma-miyagawa 
@h-yokoyama-eiwa 
@esmtodoroki 
アドバイスありがとうございます。
あらためて、４－１対応したので、確認よろしくお願いします！

2023-10-10 12:45 UTC, Itopan1108 commented
@ma-miyagawa 
@h-yokoyama-eiwa 
@esmtodoroki 
４－１指摘対応したので、確認よろしくお願いします。

2023-10-11 03:22 UTC, ma-miyagawa commented
@Itopan1108

宮川指摘分は確認しました。LGTM！

2023-10-11 04:22 UTC, esmtodoroki commented
@Itopan1108 
LGTM🍝
自分は日時を格納すると思われる項目を作らなかったので、これからどう使っていくのか注目しています

2023-10-11 10:20 UTC, h-yokoyama-eiwa commented
@Itopan1108 
テーブル名は複数形（～s）とするのがいいようですが、今回はカウントなんでまあいいか、ということでLGTMです。

2023-10-17 11:57 UTC, merged