4-5,6 DBアクセス
Itopan1108/webapp1-countup-Renew- pull request #11
Opened 2023-10-17 12:10 UTC by Itopan1108

@esmtodoroki
@h-yokoyama-eiwa
@ma-miyagawa

４－５と４－６　のプルリクエストです。
一応、コメントを入れて、４－５（DB更新）と４－６（DB参照）は、わけて見れるようには
しています。（カラムを揃えることや、最後の改行は行っています）
レビューのほど、よろしくお願いします。

2023-10-18 11:19 UTC, ma-miyagawa requested changes
@Itopan1108 

確認しました。指摘事項の対応をお願いします。
今回、テキストファイルをプッシュされていますが、main.jsに張り付けるべきでないかと思います。張り付けた後、今回プッシュしたテキストファイルをgitから削除してください。

2023-10-18 11:39 UTC, ma-miyagawa requested changes
@Itopan1108

確認しました。指摘事項の対応をお願いします。
今回、テキストファイルをプッシュされていますが、main.jsに張り付けるべきでないかと思います。張り付けた後、今回プッシュしたテキストファイルをgitから削除してください。

2023-10-18 11:39 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +
DB接続部分ですが、GitHubのリポジトリにアップされるとセキュリティ上の問題になるので
以下の手順で対応してください
　１．DB接続部分を別ファイルに切り出す
　２．切り出したファイルをimportして利用できるようにする。
　３．.gitignoreに切り出したファイルを記入して、git管理対象外にする。

2023-10-18 11:39 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  var connection = Jdbc.getCloudSqlConnection(url, userName, password);
変数定義がvarになっていますが、さまざまな場面で利用できる反面、意図しない再宣言や再代入によってエラーにつながる可能性があります。
下記サイトを読んで直してください。

https://techplay.jp/column/1619

2023-10-18 11:39 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  var statement = connection.prepareStatement('UPDATE countup SET count_number=?, updated_at=? WHERE entryID=1');
一件もない場合、insertを行う必要があります。
Mysqlにはinsertとupdateを１SQLでできるので、下記サイトを読んで修正してください。

https://dev.mysql.com/doc/refman/5.6/ja/insert-on-duplicate.html

2023-10-18 11:39 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  statement.setString(1, count_number + 1);
カウンタは数値項目なので、setInt()を使うべきです。
また、count_numberはどこにも宣言されていません。ここでは画面で入力されたカウンタが設定されるので
引数からもらった値を設定するはずです。

2023-10-18 11:39 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  statement.setdate(2, getDate);
Datetime型に値を設定している getDateですが、
DateオブジェクトのgetDate()メソッドは、日を1から31の整数で取得します。これでは更新できないです。

2023-10-18 11:39 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +}
DBから取得したカウンタを画面に返さなければならないので
戻り値を設定する必要があります。

2023-10-19 06:50 UTC, esmtodoroki commented on DB update and read 4-5,6.txt
> +function updateOneRecord() {
関数名に含まれる「One」の意味がわかりませんでした。
何のレコードを指すのか適切な命名にするか、あるいは今回のアプリでは1レコードしか存在しないので、取ってしまっても良いと思います。

2023-10-19 07:29 UTC, esmtodoroki commented on DB update and read 4-5,6.txt
> +  var entryID = results.getInt('id');
機能を考えると、idの値をgetする必要はあまり無い気がしますね。

2023-10-19 07:30 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +
@ma-miyagawa
@esmtodoroki
@h-yokoyama-eiwa
cc  @toyo01 
これなのですが、 ちょっと調べてみたところ、プロパティストア　という、GASの仕組み（アドレスやキー情報など、見せたくないものを隠す機能）があるっぽいです。
以下、そちらで対応してもよいのでしょうか。（できるかどうかはやってみないとですがー）

https://tonari-it.com/gas-property-store/

2023-10-19 07:31 UTC, esmtodoroki commented
@Itopan1108 
確認しました。2点指摘しましたが、いずれも軽微な内容です。

2023-10-19 07:46 UTC, esmtodoroki commented on DB update and read 4-5,6.txt
> +
プロパティストアを使用しても良いと思いますが、
setPropertyメソッドを記述するファイルはGitに上げないようにしてくださいね。
そこにパスワード等を記述することになると思うので。

2023-10-19 10:47 UTC, h-yokoyama-eiwa commented
他のお二人がいろいろ指摘してくれているのでもう指摘することないですね。

2023-10-19 13:31 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +
@ma-miyagawa 
cc @esmtodoroki  @h-yokoyama-eiwa 
こちらの対応については、今週末、がんばります。
それ以外の対応は、完了（つもり）しました！
今から、コメントしていきますね。

2023-10-19 13:31 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var connection = Jdbc.getCloudSqlConnection(url, userName, password);
@ma-miyagawa 
cc @esmtodoroki  @h-yokoyama-eiwa 

ありがとうございます。対応しました。

2023-10-19 13:32 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var statement = connection.prepareStatement('UPDATE countup SET count_number=?, updated_at=? WHERE entryID=1');
@ma-miyagawa
cc @esmtodoroki @h-yokoyama-eiwa

ありがとうございます。なるほど、ON DUPLICATE、なんでも便利なものあるのですね。対応いたしました。

2023-10-19 13:32 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  statement.setString(1, count_number + 1);
@ma-miyagawa
cc @esmtodoroki @h-yokoyama-eiwa

ありがとうございます。たしかに、stringとなっていました。修正しました。
関数の引数として、count_number　を受け取るようにしました。（少し自信なし。。です）

2023-10-19 13:33 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  statement.setdate(2, getDate);
@ma-miyagawa
cc @esmtodoroki @h-yokoyama-eiwa

宮川さんが教えてくれた、上記記事に関連してググったところ、notNULL制約というものと、timestamp型というものを知りました。
よって、あらためて、DDLでのTBLのcreate を日付項目について、以下の定義でやりなおそうと思います。

created_at timestamp not null default current_timestamp,
updated_at timestamp not null default current_timestamp on update current_timestamp,

2023-10-19 13:35 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +}
@ma-miyagawa
cc @esmtodoroki @h-yokoyama-eiwa

ありがとうございます。そうですね。戻り値を設定しました。

2023-10-19 13:35 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +function updateOneRecord() {
@esmtodoroki 
cc @ma-miyagawa　@h-yokoyama-eiwa

ありがとうございます。関数名からOneをとって、updateRecord() としました。

2023-10-19 13:36 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var entryID = results.getInt('id');
@esmtodoroki
cc @ma-miyagawa　@h-yokoyama-eiwa

自分もそう思うので、idの取得を消しました。ありがとうございます。

2023-10-19 13:36 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  statement.setdate(2, getDate);
テーブルは、あらたに、countup2として、作ります。

2023-10-19 23:54 UTC, k-shimada-esm reviewed
@Itopan1108 
細かいところですが、追加コメントしました。

2023-10-19 23:54 UTC, k-shimada-esm commented on DB update and read 4-5,6.txt
> +var getData =  getDate()
`getData` の使い道はなんでしょうか。

2023-10-19 23:54 UTC, k-shimada-esm commented on DB update and read 4-5,6.txt
> +  var results = statement.executeQuery('SELECT * FROM countup');
`results` ということは複数レコードが返却される？

2023-10-19 23:54 UTC, k-shimada-esm commented on DB update and read 4-5,6.txt
> +  var count_number = results.getInt('count_number');
変数名はキャメルケースで。

2023-10-20 02:33 UTC, esmtodoroki commented on DB update and read 4-5,6.txt
> +  statement.setString(1, count_number + 1);
count_numberのことなんですが、ここで+1をして格納すると、フロント側（Web画面側）に表示されているカウンターの値より、1大きい値を格納することになってしまわないですかね。
例えば、初期値0からスタートし、画面で10回カウントアップを押すとカウンターは10になってるはずですが、そこで保存を押すとDBには11が格納されてしまうと思われます。
なので、ここでは素直にフロント（呼び出し元となるindex.html）から受け取った値をそのまま格納すれば良いかと。

2023-10-20 02:34 UTC, esmtodoroki commented
@Itopan1108 
追加で1点疑問に思ったことを記入しました。
確認よろしくお願いします。

2023-10-20 06:34 UTC, Itopan1108 commented
@ma-miyagawa
@esmtodoroki
@h-yokoyama-eiwa

あれ、昨夜、修正後、プッシュしたんですが、今見るとされてないですね。（コミットが３日前の１件しかない。）

夜か明日の朝に、あらためてプッシュしますので、お待ち下さいーー。。

2023-10-20 07:01 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  statement.setString(1, count_number + 1);
@esmtodoroki 
本当ですね。加算は、vue.js で実装しているんでした。指摘どおり、＋１の部分を取ります。　

2023-10-20 07:01 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +var getData =  getDate()
@k-shimada-esm 
本当ですね。これはゴミですね。消します。

2023-10-20 07:02 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var results = statement.executeQuery('SELECT * FROM countup');
@k-shimada-esm 
今回は１件ですので、単数です。sを消します。ありがとうございます。

2023-10-20 07:02 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var count_number = results.getInt('count_number');
@k-shimada-esm 
ありがとうございます。DB項目名に引きずられてました。直します。

2023-10-21 01:46 UTC, Itopan1108 commented
@ma-miyagawa
@esmtodoroki
@h-yokoyama-eiwa
@k-shimada-esm 
お休みのところすみません！
プッシュしましたので、またご確認お願いします。
嶋田さんの指摘も取り込んでいます。

（DB接続の隠しプロパティストア対応のみが、まだです）

よろしくお願いします。

2023-10-22 04:41 UTC, h-yokoyama-eiwa reviewed
@Itopan1108 
コメントしました。

2023-10-22 04:41 UTC, h-yokoyama-eiwa commented on main.js
> +   connection.commit();
commit()って必要ですか？
要らない気がするのですが。

2023-10-22 10:49 UTC, ma-miyagawa requested changes
@Itopan1108 

確認しました。コメントを追加します。

レビューする立場から言いたいことがあります。

レビューの観点として、コーディングの約束事が守られているかとか、こうしたほうが見やすいとかを見ているので、正常動作されていることは当然であり、単なるバグつぶしやっていることでないことをご理解してください。
今回は画面から動かすことはできないですが、GASは関数単体でデバッグ動作確認ができます。
　https://tenshoku-miti.com/takepon/google-apps-script-debug-method/
DBの接続機能ついて実装中だと思われますが、実装後、動作確認を行ったうえで再レビュー依頼をお願いします。

2023-10-22 10:49 UTC, ma-miyagawa commented on main.js
> +   var  countNumber = result.getInt('count_number');
①var が残っています。
②statement.executeQueryのあとでresult.next()を行わないと、result.getIntを行ってもレコードを読むことはできません。（1件も登録されていない場合もあるのでそこのところを考慮すること）

2023-10-22 10:49 UTC, ma-miyagawa commented on main.js
> +   return countNumber ;
ここでreturnすると、それ以降のDBオブジェクトの開放処理（39行目から41行目）は実行されません。

2023-10-22 10:49 UTC, ma-miyagawa commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
これでは、更新時にカウンタが更新されません。

2023-10-22 10:56 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  var connection = Jdbc.getCloudSqlConnection(url, userName, password);
漏れているところが1か所ありました。別の場所で指摘していることので、この指摘は対応済扱いにします。

2023-10-22 10:57 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  var statement = connection.prepareStatement('UPDATE countup SET count_number=?, updated_at=? WHERE entryID=1');
再レビューで追加指摘しているので、この指摘は対応済扱いにします。

2023-10-22 11:00 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +  statement.setdate(2, getDate);
テーブルの変更によってDBのシステム日時が更新されることを確認しましたので確認済とします。

2023-10-22 11:01 UTC, ma-miyagawa commented on DB update and read 4-5,6.txt
> +}
再レビューで追加指摘しているので、この指摘は対応済扱いにします。

2023-10-23 06:16 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var statement = connection.prepareStatement('UPDATE countup SET count_number=?, updated_at=? WHERE entryID=1');
承知しました。見てみます。

2023-10-23 06:16 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +}
承知しました。見てみます。

2023-10-23 06:19 UTC, Itopan1108 commented on main.js
> +   connection.commit();
@h-yokoyama-eiwa 

参考にしたものが、そうなっていたのですが、DB更新なので、毎回、DB確定（commit)が必要と
認識して、実装しました。
https://businessskillupseminar.jp.net/program/java/java06.html

実験の意味もこめて、一旦、このまま、このあとのDB接続編でやってみたく、よいでしょうか。

2023-10-23 06:24 UTC, h-yokoyama-eiwa commented on main.js
> +   connection.commit();
@Itopan1108 
参考にしたのはリンク先の「トランザクション処理」の部分ですか？

2023-10-23 06:27 UTC, Itopan1108 commented on main.js
> +   connection.commit();
@h-yokoyama-eiwa 
そうですね。（DB更新は、都度確定させないといけないんだと、理解して）

2023-10-23 06:33 UTC, h-yokoyama-eiwa commented on main.js
> +   connection.commit();
@Itopan1108 
なるほど。参考にしたソースは、「Cn.setAutoCommit(false);」
でオートコミットをoffしてるので自前でcommitが必要になってます。
一旦このままで了解しました。
次の対応時に確認してもらって、不要であれば削除してください。

2023-10-23 06:42 UTC, Itopan1108 commented on main.js
> +   var  countNumber = result.getInt('count_number');
@ma-miyagawa 
①すみません、修正しました。
②　⇒　なるほど、理解しました。
　https://java-code.jp/969
　　１レコードだけの取得でも、nextがいるのですね。ポインタは読み込んだ先頭行よりも前にあるままなので、nextで取得した１行目にポインタを移動させると理解できました。
　　そのうえで、gresult.getInt()がポインタのあるところから、取ってこれるようになる。すみません、詳細な指摘ありがとうございます。

2023-10-23 07:29 UTC, Itopan1108 commented on main.js
> +   return countNumber ;
@ma-miyagawa 
リターンはそこで、処理が終わってしまうということですね。対応します。
帰宅してから、上記のアドバイスとおり、動きを確認してから、連絡しますね。

2023-10-23 08:01 UTC, Itopan1108 commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
@ma-miyagawa 
1加算されていないという指摘でしょうか？もしそれであれば、先日轟さんの方に指摘を受け、＋１をやめています。（呼び元のvue側で加算しており、二重加算になるため）
もし、指摘が違うのであれば、すみません。不明点がわからないため、お手数ですが教えてほしいです。。

2023-10-23 10:15 UTC, ma-miyagawa commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
轟さんの指摘と違います。
実際に動かすか、SQL文を実行すれば、事象がわかると思います。

2023-10-23 12:46 UTC, Itopan1108 commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
mysqlのshellで、INSERTコマンド実行したところ、エラーとなりました。（漠然とした。。）
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near　XXXXXX
結論としては、指摘箇所は、values となっていたところだと思います。
正しくは、VALUE　ですよね？　自分が参照したサイトは　values　となっていたのですが、他のサイトを見ると、構文上、VALUE　でした。　MYSQLのバージョンで違うっぽい。
そこを、修正して、INSERTされたことを確認できました！

また、

宮川さんがご教授くれた、ON DUPLICATE KEY UPDATE　ですが、
既に、id=1　のレコードがある場合、
ON DUPLICATE KEY　にしている　id = １のレコード追加がやってきたら、追加じゃなく、更新がされる理解なのですが、違うということでしょうか？
上記、宮川さんのケースだと、３→５に更新されると思っています。
でも、きっと、宮川さんが指摘してくるということは、何か罠が潜んでいるのですよね・・？
もし、自分の書いたことが間違ってるなら、明日の会で、教えてもらってよいでしょうか？みんなで共有できる話題と
なれば。

2023-10-23 12:47 UTC, Itopan1108 commented on DB update and read 4-5,6.txt
> +  var connection = Jdbc.getCloudSqlConnection(url, userName, password);
@承知しました。

2023-10-23 12:48 UTC, Itopan1108 commented on main.js
> +   connection.commit();
@h-yokoyama-eiwa 
言っていることが理解できたので、消しました！

2023-10-23 12:49 UTC, Itopan1108 commented on main.js
> +   var  countNumber = result.getInt('count_number');
@ma-miyagawa 
こちらも、対応しましたので、ご確認お願いします。

2023-10-23 12:50 UTC, Itopan1108 commented on main.js
> +   return countNumber ;
@ma-miyagawa 
対応しましたので、またご確認のほどよろしくお願いします。

2023-10-23 12:52 UTC, Itopan1108 commented
ON DUPLICATE KEY UPDATE　のもやもやは残りますが、頂いた指摘の対応をしましたので、
なんどもすみませんが、各自ご確認お願いします。

それで、相変わらず、プロパティストアの部分だけが、残対応です。。明日やろうと思います。
よろしくお願いします。
今日は、終わりにします。

2023-10-24 04:46 UTC, esmtodoroki commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
ON DUPLICATE KEY UPDATE の所には、更新したいカラムを指定します。
現状は「id」と書かれていますが、更新したいのはidではないですよね？カウンターの値です。
なので、
ON DUPLICATE KEY UPDATE count_number = ? と書くことになるかと思います。

また、この4つ目の引数に値を編集する必要があるので、statement.setInt(4, count) を追記しましょう。

余談ですがそれがしは「ON DUPLICATE」で実装する方法を知りませんでした。なのでそれがしの勉強にもなりました。

2023-10-24 05:02 UTC, esmtodoroki commented
@Itopan1108 
ON DUPLICATE KEY UPDATE の部分は轟の勉強も兼ねて知りたいと思い、ヒントを出しました。
指摘箇所については確認できました。
たくさんの指摘取り込みと試行錯誤、お疲れさまでした。

2023-10-24 07:40 UTC, Itopan1108 commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
@esmtodoroki @ma-miyagawa 
轟さん、宮川さんに変わり、回答ありがとうございます。
いただいた情報もとに、オンデュプリケート、もうしばしみてみますね。
むずい、、

2023-10-24 07:41 UTC, k-shimada-esm commented on DB update and read 4-5,6.txt
> +var getData =  getDate()
@Itopan1108 
🙆

2023-10-24 07:42 UTC, k-shimada-esm commented on DB update and read 4-5,6.txt
> +  var results = statement.executeQuery('SELECT * FROM countup');
@Itopan1108 
🙆

2023-10-24 07:42 UTC, k-shimada-esm commented on DB update and read 4-5,6.txt
> +  var count_number = results.getInt('count_number');
@Itopan1108 
🙆

2023-10-24 13:27 UTC, Itopan1108 commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
@ma-miyagawa @esmtodoroki 
INSERT　SQL修正したので、確認お願いします。動きも確認しました。

mysql> INSERT INTO countup2 (id, count_number) values (1, 5)  ON DUPLICATE KEY UPDATE count_number = 7;
Query OK, 2 rows affected (0.16 sec)

mysql> SELECT * FROM countup2;
+----+--------------+---------------------+---------------------+
| id | count_number | created_at          | updated_at          |
+----+--------------+---------------------+---------------------+
|  1 |            7 | 2023-10-23 11:45:07 | 2023-10-24 13:23:49 |
+----+--------------+---------------------+---------------------+
1 row in set (0.15 sec)

2023-10-25 00:01 UTC, esmtodoroki commented on main.js
> +   const statement = connection.prepareStatement('INSERT INTO countup2 (id, count_number) values (?, ?)  ON DUPLICATE KEY UPDATE id = ?');
@Itopan1108 
確認しました。良さげですね👌

2023-10-25 11:35 UTC, ma-miyagawa requested changes
@Itopan1108 

readFromTable()についてコメントしました。確認の上修正してください。

2023-10-25 11:35 UTC, ma-miyagawa commented on main.js
> +
@Itopan1108 

readFromTable()で修正されていますが、不十分なので回答例を記載します。

function readFromTable() {
   const connection = Jdbc.getCloudSqlConnection(url, userName, password);
   const statement = connection.createStatement();
   const result = statement.executeQuery('SELECT * FROM countup2');
   // countNumberを初期化する。countNumberは再代入するのでlet
   let countNumber = 0;
   while (result.next()) {
    // countNumberにDBから取得した値を設定する
    countNumber = result.getInt('count_number');
    Logger.log(countNumber);
   }

   result.close();
   statement.close();
   connection.close();
   // DBのオブジェクトを開放してから呼び先に戻る
   return countNumber;
 }
 
 ※countNumberはオブジェクトでなく数字型なので、isEmptyは使えない。

2023-10-25 14:09 UTC, Itopan1108 commented
@ma-miyagawa
@esmtodoroki
@h-yokoyama-eiwa
@k-shimada-esm

プロパティストア対応し、
プッシュしましたので、よろしくお願いします！
（DB接続の記述は、先頭ではなく、4-5.6の関数の手前に入れました。）

これで、４－５、６が終わりますように！ご確認よろしくお願いします。

2023-10-25 23:38 UTC, k-shimada-esm commented on main.js
> +   while (result.next()) {
@Itopan1108 
next 読みするのであれば、result は複数形 `results` にしたほうがよいですね。
必ず 1 件であれば、`if (result.next()) {`  で判定すればよいと思います。
※実開発では単数形か複数形かを意識して変数定義しているで、あえてこだわらせていただきました。

2023-10-25 23:46 UTC, k-shimada-esm commented on main.js
> +   while (result.next()) {
@Itopan1108 
> const result = statement.executeQuery('SELECT * FROM countup2');

ちなみに、SELECT文を見ると、主キーで条件指定していないので、複数レコードが返ってくる形ですね。
この場合なら複数形としたほうがよさそうですね。

2023-10-26 06:08 UTC, Itopan1108 commented on main.js
> +
@ma-miyagawa 
ありがとうございます。
宮川さんの知識と、的確な指摘に、脱帽です。
理解し、修正します！

2023-10-26 06:28 UTC, Itopan1108 commented on main.js
> +   while (result.next()) {
@k-shimada-esm 
嶋田さんも、礼儀正しくお作法をしっかり指摘してくれて、とても助かります。頭が下がります。
単数形、複数形意識します。

今回の場合、アドバイスどおり、if 文に変更してみようと思います。
SQLも、
SELECT * FROM countup2 WHERE id = 1　と、WHERE句をつけるようにします。

2023-10-26 06:50 UTC, esmtodoroki commented on main.js
> + const url = PropertiesService.getScriptProperties().getProperty("url");
connectionNameとdatabaseNameはurlに含まれているはずなので、urlをプロパティストアで正しく編集出来ているのであれば、ここで定義する必要はないかなと思いました。
あと、DB接続情報みたいな固定値項目を宣言する時は、大文字でスネークケースで記述することが慣例となっています。
「userName」は「USER_NAME」といった感じです。

2023-10-26 06:55 UTC, esmtodoroki commented on main.js
> +     return ZERO;
結果的にボツになるようですが、「return ZERO」とCOBOLみたいに表意文字使えるんでしたっけ？

2023-10-26 14:35 UTC, Itopan1108 commented on main.js
> +     return ZERO;
@esmtodoroki 
大丈夫と思って書いたんですが、
指摘されると不安になるもので。。今、ググったんですが、結論がわかりませんでした。

2023-10-26 14:45 UTC, Itopan1108 commented on main.js
> + const url = PropertiesService.getScriptProperties().getProperty("url");
@esmtodoroki 
urlに含まれているという意味はわかりました。そのうえで、今のプロパティストアの定義のまま、いかせてほしいです。DB接続情報固定値項目の慣例は知りませんでした。修正します。

2023-10-26 14:51 UTC, Itopan1108 commented
@esmtodoroki 
@k-shimada-esm 
指摘ありがとうございます！確認し、修正すべきところは修正してみたので、
確認及び承認お願いします！

2023-10-26 23:27 UTC, k-shimada-esm commented on main.js
> +   while (result.next()) {
@Itopan1108 
🙆

2023-10-26 23:35 UTC, Itopan1108 commented on main.js
> +     return ZERO;
[@esmtodoroki](https://github.com/esmtodoroki)
大丈夫と思って書いたんですが、
指摘されると不安になるもので。。今、ググったんですが、結論がわかりませんでした。
そして、あらためて、return ZERO;を実装し、「デバッグ」を実行してみたところ、問題なさそうです！
もとに戻します。

2023-10-26 23:36 UTC, Itopan1108 commented
@esmtodoroki
@k-shimada-esm
指摘ありがとうございます！確認し、修正すべきところは修正してみたので、
４−５，６確認及び承認お願いします。

2023-10-27 00:13 UTC, esmtodoroki commented on main.js
> + const url = PropertiesService.getScriptProperties().getProperty("url");
了解しました。
固定値項目の表記修正、確認しました。

2023-10-27 00:14 UTC, esmtodoroki commented on main.js
> +     return ZERO;
試してくれてありがとうございました。
自分もネット検索したんですが、回答にたどり着けなかったです。

2023-10-27 00:17 UTC, esmtodoroki commented
@Itopan1108 
readFromTable関数内の下記で使用している引数が修正前のままなので、このままでは動かないと思います。
Jdbc.getCloudSqlConnection(url, userName, password)

2023-10-27 11:28 UTC, Itopan1108 commented
@ma-miyagawa
@esmtodoroki
@h-yokoyama-eiwa
@k-shimada-esm

轟さんの通り、直し漏れがありましたね。新人みたいですみません。
修正しましたので、お手数ですが、最終確認お願いします！

これから、福井へ移動します。
明後日のBOTの会は、予定があり、1時間ちょいは出れます。よろしくお願いします。

2023-10-29 06:09 UTC, esmtodoroki commented
LGTM🍊

2023-10-29 14:05 UTC, ma-miyagawa commented
LGTM
長い間おつかれさまでした

2023-11-03 23:50 UTC, merged