4-8 Promiseとローディング対応
Itopan1108/webapp1-countup-Renew- pull request #13
Opened 2023-11-19 02:54 UTC by Itopan1108

@esmtodoroki
@h-yokoyama-eiwa
@ma-miyagawa

４－８対応が完了しました。
Promise大変でした。

VOverlay（ローディング）対応の方は、DB読み込みの方だけじゃなくて、DB更新の方も対応すればよかった
ですよね？コメント入れて対応しました。
DB更新の方は、setTimeoutを使用し、3秒後にオーバーレイを非表示するやり方でやってみました。
setTimeout(() => {
      this.isLoading = false;
    }, 3000);

ご確認よろしくお願します。

2023-11-19 06:14 UTC, ma-miyagawa commented
@Itopan1108 

字下げがなくなっているため、全ステップに差分が発生しています。
これでは何を修正したのかわかりにくいので、字下げをした状態のもので再度、提出してください。

プッシュしたときに「Files Changed」タグで差分の確認を行ったほうがよいです。

2023-11-19 07:27 UTC, Itopan1108 commented
@esmtodoroki
@h-yokoyama-eiwa
@ma-miyagawa

失礼しました。気をつけます。

（それ以外、気が付いたところの、既存の字下げも微修正したので、
　少し差分が出ています。）

対応しましたので、再度、プルリクします。
よろしくお願いします。

2023-11-20 06:53 UTC, esmtodoroki commented on index.html
> +     async function GasReadAsync() {
関数はここに記述せずに、methods: の中に書きましょう。

2023-11-20 06:56 UTC, esmtodoroki commented on index.html
> +       isLoading: true,
変数を定義するとき、boolean型の変数の初期値はfalseが基本です。
data: のところではfalseで定義して起き、処理の中でDB読み込みの直前にtrueにしましょう。

2023-11-20 07:01 UTC, esmtodoroki commented on index.html
> +      return await new Promise((resolve, reject) => {
この行にawaitは不要だと思います。

2023-11-20 07:12 UTC, esmtodoroki commented
DB更新時に3秒待ってローダーをオフにするやり方は、実用上は問題ないと思いますが、読み込み時と同じようにPromise返却を受けたうえでオフにするほうが好ましい気がします。
他のレビューワーの意見も聞いてみたいところです。

2023-11-20 10:16 UTC, h-yokoyama-eiwa requested changes
@Itopan1108 
コメントしました。

2023-11-20 10:16 UTC, h-yokoyama-eiwa commented on index.html
> +      .readFromTable();
成功した時も失敗した時も両方resolveになってますけれど、失敗した時はrejectなのでは。

2023-11-20 10:16 UTC, h-yokoyama-eiwa commented on index.html
> +     async function GasReadAsync() {
関数名から処理が分かりにくいですね。
ガスを読むとは。

2023-11-20 10:16 UTC, h-yokoyama-eiwa commented on index.html
> +        output: async function() {
関数名と処理内容のイメージが合わないんですが、私だけでしょうか。

2023-11-20 10:16 UTC, h-yokoyama-eiwa commented on index.html
> +         }, 3000);
せっかく同期処理にしているのに時間でオーバーレイOFFするのってなんかもったいない気がします。
処理が終わったらOFF、ってやるほうがいいんじゃないかなと思います。

2023-11-20 10:35 UTC, ma-miyagawa requested changes
@Itopan1108 

確認しました。対応をお願いします。

2023-11-20 10:35 UTC, ma-miyagawa commented on index.html
> +     async function GasReadAsync() {
async も不要です。

2023-11-20 10:35 UTC, ma-miyagawa commented on index.html
> +
105行目から108行目は、不要です。（同期化の意味がない）
ローディングのオン⇒GasUpdateAsync⇒ローディングのオフで同期化ができていることを確認できます。

2023-11-20 10:35 UTC, ma-miyagawa commented on index.html
> +     }
GAS側でエラーが発生することも想定されるため、68行目から72行目の書き方に合わせてください。

2023-11-20 10:35 UTC, ma-miyagawa commented on index.html
> +
呼び出している関数内で、正常の場合とエラーの場合の記載があるので、呼び出し元もエラーの対応を行ってください。（カウンタを更新しているところも同様）

下記サイトを参考に対応してください。（マンガ形式なので分かりやすいはずです）
https://manga.crocro.com/?cat=js_promise&pg=index

2023-11-20 13:07 UTC, k-shimada-esm commented on index.html
> +     async function GasReadAsync() {
>関数名から処理が分かりにくいですね。
>ガスを読むとは。

補足として。
関数名の命名作法として、「動詞＋目的語」を英語、小文字から始まるキャメルケースで。
私がいつもやっているやり方が参考になるかどうか分からないですが。

```
・関数でやりたいことをコメントで書く。
・コピペして翻訳してみる。
・第三者が直観で分かるように整える。（英語の使い方を間違えないように、）
```
```
例えば、「カウンター値を情報する。」を翻訳してみる。⇒ Get counter information
/**
 * カウンター情報を取得する。
 */
function getCounterInfo() {
```

2023-11-24 07:20 UTC, Itopan1108 commented on index.html
> +      .readFromTable();
@h-yokoyama-eiwa 
ほんとだ。。対応しました。

2023-11-24 07:31 UTC, Itopan1108 commented on index.html
> +        output: async function() {
initDataの関数は、未使用でした。消し漏れです。消しました。

2023-11-25 02:01 UTC, Itopan1108 commented on index.html
> +      return await new Promise((resolve, reject) => {
@esmtodoroki 
ありがとうございます。対応しました。

2023-11-25 02:02 UTC, Itopan1108 commented on index.html
> +         }, 3000);
みんなの意見どおり、対応しました！

2023-11-25 02:02 UTC, Itopan1108 commented on index.html
> +     async function GasReadAsync() {
@ma-miyagawa 
ありがとうございます。対応しました。

2023-11-25 02:03 UTC, Itopan1108 commented on index.html
> +
@ma-miyagawa 
ありがとうございます。対応しました。

2023-11-25 02:03 UTC, Itopan1108 commented on index.html
> +     }
@ma-miyagawa 
ありがとうございます。対応しました。

2023-11-25 02:04 UTC, Itopan1108 commented on index.html
> +
@ma-miyagawa 
ありがとうございます。この漫画めちゃわかりやすいですね！（といっても、やっぱり、めちゃ難しいですが。。）
とてもためになる本（PDF）だと思い、500円で購入しておこうと思います。

2023-11-25 02:08 UTC, Itopan1108 commented
@ma-miyagawa @esmtodoroki 
cc @h-yokoyama-eiwa @k-shimada-esm 

以下の２点が、自分だけで解消できません。。明日のBOTの会の終わりにでよいので、少しレクチャー・指導をいただいてもよろしいでしょうか（；；）
よろしくお願いします。

　・関数はここに記述せずに、methods: の中に書きましょう。

　・呼び出している関数内で、正常の場合とエラーの場合の記載があるので、呼び出し元もエラーの対応を行ってください。　（カウンタを更新しているところも同様）

それ以外は修正完了しました。最新状態の、index.htmlを、以下貼り付けておきますね。


<!DOCTYPE html>
<html iang="ja">
  <head>
    <base target="_top">
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.1/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.7/dist/vuetify.min.css" rel="stylesheet">
  </head>
 
  <body>
    <!-- カウントアップ対応 -->
    <div id="app">
     <v-app>
       <!-- ローディング中は、オーバーレイを表示 -->
       <v-overlay :value="isLoading">
        <v-progress-circular 
         indeterminate 
         color="purple" 
         size="64" />
        </v-progress-circular>
       </v-overlay>

      <v-container fluid>
       <v-row
        class="blue lighten-4" style="height: 700px;"
        justify="center" align-content="center"
       >
        <v-col
         cols=12 sm=12 md=8 lg=4 xl=3
        >

         <v-card color="white" shaped>   
          <v-row class="text-h1 text-center pink--text" style="height: 100px;" justify="center">{{count}}</v-row>
          <v-row class="text-h6 text-center"  style="height: 50px;" justify="center">回カウントしたよ</v-row>
         </v-card>

         <v-card color="green" >
          <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn height="100" width="100" rounded v-on:click="increment" class="text-h5">加算</v-btn>
          <v-spacer></v-spacer>
          <v-btn height="100" width="100" rounded v-on:click="clear" dark class="text-h5">初期値</v-btn>
          <v-spacer></v-spacer>
          </v-card-actions>
         </v-card>

         <v-card color="yellow" >
          <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn height="100" width="100"  outlined color="primary" v-on:click="output" class="text-h5">更新</v-btn>
          <v-spacer></v-spacer>
          </v-card-actions>
         </v-card>

        </v-col>
       </v-row>
      </v-container>
     </v-app>
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.11/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.7/dist/vuetify.js"></script>
    <script >
    
     function getCounterInfo() {
      return new Promise((resolve, reject) => {
      google.script.run
      .withSuccessHandler((result) => resolve(result))
      .withFailureHandler((error) => reject(error))
      .readFromTable();
      });
     }
      
     function updateCounterInfo(count) {
      return new Promise((resolve, reject) => {
      google.script.run
      .withSuccessHandler((result) => resolve(result))
      .withFailureHandler((error) => reject(error))
      .updateRecord(count)
      });
     }

      new Vue({
       el: '#app',
       vuetify: new Vuetify(),
       data: {
       count: "",
       //ローディングの初期値はfalse
       isLoading: false,
       },
       created: async function(){
        this.isLoading = true;
        this.count = await getCounterInfo();

        // ローディングが終わったら、オーバーレイ表示をオフ
        this.isLoading = false;
       },
       methods: {
        increment: function() {
         this.count += 1
         },
        clear: function() {
         this.count = 0
         },

        //getCounterInfo: function() {
        // return new Promise((resolve, reject) => {
        // google.script.run
        // .withSuccessHandler((result) => resolve(result))
        // .withFailureHandler((error) => reject(error))
        // .readFromTable();
        //});
        //},

        output: async function() {
         // ＤＢ更新中は、オーバーレイ表示
         this.isLoading = true;
         await updateCounterInfo(this.count);
         // オーバーレイ表示をオフ
         this.isLoading = false;
        },            
       }
      })
    </script>
  </body>

2023-11-26 06:18 UTC, Itopan1108 commented on index.html
> +     async function GasReadAsync() {
@esmtodoroki  @k-shimada-esm 
関数を vue内に記載出来ました。　this.がポイントでした。

関数名も、いい感じにできました。

2023-11-26 06:18 UTC, Itopan1108 commented on index.html
> +       isLoading: true,
@esmtodoroki 
ありがとうございます。修正しました。

2023-11-26 06:19 UTC, Itopan1108 commented on index.html
> +        output: async function() {
@h-yokoyama-eiwa 

関数名はわかりやすく、対応しました。ありがとうございます。

2023-11-26 06:20 UTC, Itopan1108 commented on index.html
> +
@ma-miyagawa @k-shimada-esm @h-yokoyama-eiwa 
先ほどは、対面（オンライン）指導ありがとうございました。
よく理解できました。
更新の方も、try catch対応しました。（テスト済）

2023-11-26 09:48 UTC, Itopan1108 commented
@h-yokoyama-eiwa 
@ma-miyagawa 
@esmtodoroki 

4-8 たくさんの指摘ありがとうございました。
対応完了しました。
確認のほどよろしくお願いします。
（カリキュラム達成しますように！）

2023-11-27 10:21 UTC, h-yokoyama-eiwa requested changes
追加でコメントしました。

2023-11-27 10:21 UTC, h-yokoyama-eiwa commented on index.html
> +        alert (e)
ここalertは字下げしときましょ。

2023-11-27 10:21 UTC, h-yokoyama-eiwa commented on index.html
>           },
閉じ括弧の位置はもう一つ左がいいですね。

2023-11-27 10:21 UTC, h-yokoyama-eiwa commented on index.html
> +
ここも字下げしていきましょう。
getCounterInfoの閉じ括弧とPromise後のアロー関数の閉じ括弧が同じ位置になってますので、閉じ括弧を一つ右にして｛｝内も字下げしましょう。

2023-11-27 10:21 UTC, h-yokoyama-eiwa commented on index.html
> +        output: async function() {
Db～の名前に変更したのってどこですか？
どこ直ってるのかわからなくなってしまった。。。

2023-11-27 11:14 UTC, ma-miyagawa commented on index.html
> +     async function GasReadAsync() {
確認しました。🙆

2023-11-27 11:14 UTC, ma-miyagawa commented on index.html
> +
確認しました。🙆

2023-11-27 11:15 UTC, ma-miyagawa commented on index.html
> +     }
確認しました。🙆

2023-11-27 11:15 UTC, ma-miyagawa commented on index.html
> +
確認しました。🙆

2023-11-27 11:21 UTC, ma-miyagawa commented
@Itopan1108 

コメントしました。
index.htmlの66～82行目は削除してください。（移動していらなくなったはずなので）

2023-11-27 14:07 UTC, Itopan1108 commented on index.html
> +        alert (e)
@h-yokoyama-eiwa 
しましたー

2023-11-27 14:09 UTC, Itopan1108 commented on index.html
>           },
@h-yokoyama-eiwa 
なおしましたー

同様に、incrementもだったので、なおしましたー

2023-11-27 14:11 UTC, Itopan1108 commented on index.html
> +
@h-yokoyama-eiwa 
対応しました！

2023-11-27 14:15 UTC, Itopan1108 commented
@h-yokoyama-eiwa 
Db～の名前に変更したのってどこですか？
どこ直ってるのかわからなくなってしまった。。。

これは、その後の嶋田さんの命名規約のご指導により、対応したので、Db～では無くなっています。
混乱させてごめんなさい。

@ma-miyagawa 
消し忘れていました！ありがとうございます。けしました。

2023-11-27 14:20 UTC, Itopan1108 commented
確認よろしくお願いします。

2023-11-27 23:57 UTC, k-shimada-esm commented
@Itopan1108 
最後のタスクになるんでしょうか。
レビューワの方が細やかなところまでご指摘して頂いているので、特には記載しませんでしたが。
アプリ開発２に入る前に、私が山川さんからご指導して頂いたことを記載しておきます（覚えている限り）ので、今後、意識して頂けると。。。
1. コメントは適宜入れること。
- 多すぎず、少なすぎず。第三者が見て分かりやすい内容で。イメージとしては、数か月後、自分がソースを見返した時に何をやっている処理か分かるか。
- 今回のカリキュラムでは関数の前にコメントが入っていなかったので、関数名で判断する必要がありました。関数ヘッダは欲しかったですね。関数ヘッダには関数でやっていることを記載するだけでなく、引数や返却値の説明も必要になります。
- また、変数もコメントがあるとよいですね。特にフラグ系はどういうときに on とするか。例えば「let disableValidate = false」は「入力チェックを無効にする場合true」のように。
2. できれば簡略系で。
- method に記載する関数は、「increment: function() {}」ではなく、「increment() {}」とも書けます。
- vue のイベントは「@」で記載できます。例えば、「v-on:click="clear"」は「@click="clear"」とも書けます。
- 今回のカリキュラムにはありませんでしたが、無名関数はアロー関数で記述します。

2023-11-28 04:14 UTC, esmtodoroki commented on index.html
> +     async function GasReadAsync() {
確認しました👍

2023-11-28 04:15 UTC, esmtodoroki commented on index.html
> +       isLoading: true,
確認しました👍

2023-11-28 04:15 UTC, esmtodoroki commented on index.html
> +      return await new Promise((resolve, reject) => {
確認しました👍

2023-11-28 04:21 UTC, esmtodoroki commented
自分の1回目の指摘について、全て対応されていることを確認しました。
エラー処理を行うtry、catchの書き方ですが、
`try {`
`  処理を記述`
`} catch(e) {`
`  エラー処理を記述`
`}`
と書くと見やすくなります。

2023-11-28 10:35 UTC, h-yokoyama-eiwa commented
@Itopan1108 
指摘箇所が修正されていることを確認しました。
LGTM！

2023-11-28 11:25 UTC, ma-miyagawa commented
@Itopan1108 

確認しました。LGTM　🙆
今回WEB開発１の最後なので轟さんからもLGTMもらっておきましょう。

2023-11-28 14:19 UTC, Itopan1108 commented
@esmtodoroki 
轟さん、修正しました。確認お願いします。
そして、最後の一言、よろしくお願いします。。

2023-11-29 04:16 UTC, esmtodoroki commented
@Itopan1108 
確認しました。LGTM🍛
なおtry文は77行目にもあるので、後で同じように整形してもらえればと思います。
長い間お疲れさまでした☕

2023-11-29 14:26 UTC, Itopan1108 commented
@esmtodoroki
ｃｃ
@h-yokoyama-eiwaya
@ma-miyagawa
try catch もう一つ、字下げ対応しました。（テストも済み）
ミス多いですね。。

それではありがとうございました！
次もよろしくお願いします。

2023-11-29 14:26 UTC, merged