Develop3 1
Itopan1108/webapp1-countup-Renew- pull request #8
Opened 2023-09-17 12:45 UTC by Itopan1108

@宮川正和 @横山宏明 @轟敦郎 
ｃｃ　@豊岡久実 　@ksakai 　@k_shimada 

３－１vue.jsの対応が完了したので、レビューお願いします。
（加算の部分と、初期化の部分をvue.jsで実装しています）

よろしくお願いします。

2023-09-18 12:09 UTC, ma-miyagawa requested changes
@Itopan1108 

確認しました。
指摘を記載しましたので対応をお願いします。
（Vueの記載になっているところとなっていないところが混在しているのではないかと思います）

2023-09-18 12:09 UTC, ma-miyagawa commented on index.html
> +    <br><input type="submit" id='submit' onclick='output()' /></br>
加算と初期化と同様に、outputも
output: function() {
     ・・・・・・
}
で記載するようにしてください。

2023-09-18 12:09 UTC, ma-miyagawa commented on index.html
> +      })
window.addEventListener("load"… でdoget関数を呼ぶようになっていますが、
Vueの場合は、createライフサイクルフックを使用してください。Vue.jsのP.45参照
そこから、GASを呼び出して、スプレットシートに保存している値を取得して初期表示させます。

2023-09-19 11:20 UTC, h-yokoyama-eiwa requested changes
@Itopan1108 
コメントしました。

2023-09-19 11:20 UTC, h-yokoyama-eiwa commented on main.js
>  function doGet(e) {
「e」って使ってます？
あったらダメってことはないですが、使ってないなら書かない方がシンプルかなって。

2023-09-19 11:20 UTC, h-yokoyama-eiwa commented on main.js
> +  const ss = SpreadsheetApp.openById('10GkWRFS8PaaOk8r0YBU7P5xu4oyLSpUJH196g5j-REs');
変数名は何の値が入っているかわかりやすい名称にしましょう。
下の「setSheetData」関数内では「spreadsheet」にしてますよね？

2023-09-19 11:20 UTC, h-yokoyama-eiwa commented on index.html
> +      let count = Number("<?= values ?>");
「values」って配列ですよね？
配列をNumberで無理やり数字にしているのがなんか違和感あります。
スプレッドシートから値を取得するときに、getValuesを使って取得した配列をそのまま返却しているようですが、WEBカウンターの場合必要な値は一つなので、getValueにするか必要な要素だけ返却した方がいいかなと思います。

2023-09-19 11:48 UTC, Itopan1108 commented on main.js
>  function doGet(e) {
これはなくていいのですね。
参考にしたものが、(e)となっていたので、おまじない程度で記載していました。。
たしかに、取っても、同じように動くことを確認したので、取りました！
受け渡すための、e という名前の項目ってことですね。呼び元から受け取って使わないなら不要ということ。

2023-09-19 11:58 UTC, Itopan1108 commented on main.js
> +  const ss = SpreadsheetApp.openById('10GkWRFS8PaaOk8r0YBU7P5xu4oyLSpUJH196g5j-REs');
@h-yokoyama-eiwa 
ss の項目名も、何か参考にしたやつのままですね。spreadsheetの略語としてのss。
指摘を受けたので、spreadsheet　へ変更しました。（修正後の動きも確認済）
ちなみに、doget関数でも、setSheetData関数でも、同じ変数名で定義することになりますが、
これは、結果、同じファイル同じシート、同じレンジを参照しているので問題ないですが、
別のファイルやシート、レンジを指すのであれば、変数も別名で定義しないとだめですよね？当たり前だけど、
聴いときたいと。

2023-09-19 12:04 UTC, Itopan1108 commented on index.html
> +      let count = Number("<?= values ?>");
@h-yokoyama-eiwa 
なるほど、value "s" か。意識してなかった。。
一つの項目を取るだけだと、getvalue()でよいと、以下、確認しました！
よって、getvalueに変更しますね。

https://uxmilk.jp/25841

2023-09-19 12:13 UTC, h-yokoyama-eiwa commented on main.js
> +  const ss = SpreadsheetApp.openById('10GkWRFS8PaaOk8r0YBU7P5xu4oyLSpUJH196g5j-REs');
変数のスコープを意識してもらって、同じ変数名でもスコープが違うなら問題ありません。
同じスコープ内の場合は当然に別の変数名を割り当てます。
スプレッドシートなら、どのスプレッドシートなのか分かるような変数名にするといいですね。

https://jsprimer.net/basic/function-scope/

2023-09-22 11:29 UTC, Itopan1108 commented on index.html
> +    <br><input type="submit" id='submit' onclick='output()' /></br>
指摘対応しました。
すっきりしました。

2023-09-22 11:30 UTC, Itopan1108 commented on index.html
> +      })
こちらは、そもそも、 window.addEventListener("loadの記述が不要だったようです。。
dogetは、サイトのリンクを踏んだときに勝手に起動されるようです。
消しても、問題なく動いたので、消しました。

2023-09-22 11:32 UTC, Itopan1108 commented
@esmtodoroki　@ma-miyagawa　@h-yokoyama-eiwa
ｃｃ　@toyo01 　@Ksakai 　@k-shimada-esm
３－１指摘対応を行いました。レビューをお願いします。
すべてを、vue.jsで記述できました。

2023-09-23 14:24 UTC, k-shimada-esm commented
上記リンクを起動したら、コンソールにエラーとワーニングが出ていますね。
ご対応をお願いします。
![image](https://github.com/Itopan1108/webapp1-countup-Renew-/assets/67683070/d486ac13-faf2-4d5c-9d84-31bcb365bce4)
![image](https://github.com/Itopan1108/webapp1-countup-Renew-/assets/67683070/36fb3611-e93a-4c94-ae64-508c65d4a0c5)

2023-09-24 13:11 UTC, ma-miyagawa commented on index.html
> +    <br><input type="submit" id='submit' onclick='output()' /></br>
こちらの指摘についての修正は問題なしです。

2023-09-24 13:11 UTC, ma-miyagawa commented on index.html
> +      })
window.addEventListenerを消したことに関しては問題ありません。

説明不足だったのかもしれません。
dogetで記載すれば、サイトのリンクをトリガとして動作するので表示はできますが、
Vueで記載するように変更するのであれば、create（またはmount）ライフサイクルフックを
トリガとして動作するように修正する必要があります。そのためこの指摘を記載していました。

下記サイトを参考にして対応をお願いします。
https://qiita.com/kyhei_0727/items/761aabac5d6ab6807249

2023-09-24 13:11 UTC, ma-miyagawa commented
@Itopan1108 

確認しましたが、初期表示分については、再度指摘を行いましたので対応をお願いします。

2023-09-26 10:36 UTC, h-yokoyama-eiwa commented
@Itopan1108 
main.jsが直っていないようですが。。。

2023-09-26 23:34 UTC, k-shimada-esm commented
@Itopan1108 
> 上記リンクを起動したら、コンソールにエラーとワーニングが出ていますね。

以前から出ているエラーで、このエラーは無視してかまわないと言われていました。
惑わせてごめんなさい。<(_ _)>

2023-09-28 10:49 UTC, Itopan1108 commented
@ma-miyagawa 
cc チャレンジャーのみなさん

嶋田さんのご協力もあり、ご指摘対応できました。
レビューのほど、お願いいたします。

> 
> 確認しましたが、初期表示分については、再度指摘を行いましたので対応をお願いします。

2023-09-28 13:24 UTC, ma-miyagawa commented on index.html
> +      })
直っていることを確認しました。

2023-09-28 13:24 UTC, ma-miyagawa commented
@Itopan1108 

宮川指摘分については、LGTM！

2023-09-29 13:42 UTC, merged