3-2 vuetify対応
Itopan1108/webapp1-countup-Renew- pull request #9
Opened 2023-09-29 13:45 UTC by Itopan1108

[@宮川正和](https://esm-all.slack.com/team/U040A2DEEUC)

[@横山宏明](https://esm-all.slack.com/team/U04010L99QW)

[@轟敦郎](https://esm-all.slack.com/team/U03V71TTXKR)

cc 
[@豊岡久実](https://esm-all.slack.com/team/U040X9BC6L8)

[@ksakai](https://esm-all.slack.com/team/U0401037UB0)

[@k_shimada](https://esm-all.slack.com/team/U04010L82R4)

[@hyamakawa(hansode)](https://esm-all.slack.com/team/U0407F314Q3)

3-2222 のvuetifyの対応が終わったので、レビューよろしくお願いします。
スケジュールに対して時間もなくなってきたので、ペースをあげていかないとと思っています。
次のDB編を進めていきます。
何卒よろしくお願いします。

2023-10-03 11:17 UTC, h-yokoyama-eiwa requested changes
@Itopan1108 
コメントしました。

2023-10-03 11:17 UTC, h-yokoyama-eiwa commented on index.html
> +      </v-card>
インデント気にしましょう。
<p>は<v-card>より字下げすると階層が分かりやすくなると思いますよ。

2023-10-03 11:17 UTC, h-yokoyama-eiwa commented on index.html
> +      <v-card rounded color="green" max-width="100%" shaped elevation="9">
roundedとshapedって同時に指定して意味ありますかね？
roundedしか有効になっていないような気がします。

2023-10-03 11:17 UTC, h-yokoyama-eiwa commented on index.html
> +      <v-card rounded color="green" max-width="100%" shaped elevation="9">
↓これは対応してもしなくてもどっちでもいいです。
せっかくroundedを指定しているのに、max-widthが100%だったり角が小さかったりであまり目立たないのが残念です。
max-widthを下げたり、角をもっと大きくしたりしてみてもいいかなと思いました。

2023-10-04 07:15 UTC, esmtodoroki commented on index.html
> +      <p class="text-h1 text-center pink--text">{{count}}</p>
Vuetifyを使う際はpタグを使わずにv-lowを使うのが基本になります。
v-lowで行、v-colで列を指定できます。
試してみてください。

2023-10-04 07:30 UTC, esmtodoroki commented
コメントしたので確認お願いします。
重複になるので書きませんでしたが、横山さんが指摘してる通りインデントに留意してもらうと見やすくなります。
カリキュラムの要件が「見栄え良く」なので、ページ内に表題的なものが欲しいところです。簡素に「カウンター」と書くだけでも、何を提供するページなのか一目瞭然になりますので。

2023-10-04 10:55 UTC, ma-miyagawa requested changes
@Itopan1108 

コメントしました。重複している指摘は記載していません。
指摘に記載しませんでしたが、ボタンの名前は、「加算」、「初期化」、「更新」のままのほうがよいと思います。日本語、英語、数字と混在していると見た目に混乱を招くように思えます。

2023-10-04 10:55 UTC, ma-miyagawa commented on index.html
> +      <p class="text-h1 text-center pink--text">{{count}}</p>
v-lowでなくv-rowですね。

2023-10-04 10:55 UTC, ma-miyagawa commented on index.html
> -
`no newline at end of file` の警告がでてますね、解消してください！（今回の修正で最後の行が消されたと思われます）

[なぜ行末空白削除と改行が必要なのか？](https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html)

2023-10-04 13:00 UTC, Itopan1108 commented on index.html
> +      </v-card>
@h-yokoyama-eiwa 
インデント意識して直しました！
気持ちいいですね。（雑でごめんなさい）

2023-10-04 13:02 UTC, Itopan1108 commented on index.html
> +      <v-card rounded color="green" max-width="100%" shaped elevation="9">
@h-yokoyama-eiwa 
確かに、roundedとshaped　を削ったりして試しましたが、意味なさそうですね。roundedの方を消しました。
というか、更に大きく作り変えました。v-row や v-colを定義して、デザインを変えました。
見てみてください。

2023-10-04 13:04 UTC, Itopan1108 commented on index.html
> +      <p class="text-h1 text-center pink--text">{{count}}</p>
@esmtodoroki 
これなのですが、ちょうど、v-rowやv-colで対応したのですが、<p>をv-colで定義するのではないですよね？
何個かサイト調べたのですが、<p>はvuetifyでも使用していて。
もう一度、見てみてもらってよいでしょうか。すみません。

2023-10-04 13:06 UTC, Itopan1108 commented on index.html
> -
@ma-miyagawa 
＋１やZEROのボタン表示は、デザインを考えたのですが、、宮川さんがあまり好きじゃないのであれば、
直しました！（自分もこだわりはなかったので）
ありがとうございます。
末尾の改行は入れました。取れてしまってましたね。添付のサイトも読みました！

2023-10-04 13:07 UTC, Itopan1108 commented on index.html
> +      <p class="text-h1 text-center pink--text">{{count}}</p>
@esmtodoroki 
轟さんの、ページ内に表題的なものが欲しいところです
というアドバイスに対しての修正（コメント）もしています。よろしくおねがいします。

2023-10-04 13:10 UTC, Itopan1108 commented
@esmtodoroki 
@h-yokoyama-eiwa 
@ma-miyagawa 

3-2vuetifyの指摘修正対応を行いました。
コミットが３つ飛んでいるかと思いますが、一番最後のをみてもらえれば
と思います。
よろしくお願いします。

2023-10-04 14:14 UTC, esmtodoroki commented on index.html
> +      <p class="text-h1 text-center pink--text">{{count}}</p>
@Itopan1108 
カウンターの値を表示する行と、「回カウントしたよ」の行がpタグで書かれてたので、ここもv-rowでそれぞれの行を書けるのではないかと思いました。
他の所はv-row、v-colで記述できてますね。

表題と書いたのでは、画面に出す文字としての表題という意味です。
いちばん上の行あたりに「カウンター」と表示してもらえれば良いと思いました。
ちなみにヘッダー部でtitleタグを使ってページタイトルを定義してますが、ブラウザーのタブにはここで定義したタイトル表示されず、URLが表示されてると思います。これはGAS特有の仕様です。一般のWebサーバーではきちんと表示されるので参考までに。

2023-10-04 15:05 UTC, Itopan1108 commented on index.html
> +      <p class="text-h1 text-center pink--text">{{count}}</p>
@esmtodoroki 
轟さんありがとうございます。
たしかに、出来ました。
あと、そうですねヘッダーはアドレスになっていました。
こちらも、ググって対応しました！

https://tonari-it.com/gas-web-html-set-title/

2023-10-04 15:06 UTC, Itopan1108 commented
@esmtodoroki
@h-yokoyama-eiwa
@ma-miyagawa
今、指摘を受けた、轟さんの対応も完了できました。
計４つ目が来てると思いますが、４つ目を見て頂ければ。

それではおやすみなさい。

2023-10-05 00:27 UTC, esmtodoroki commented
@Itopan1108 
夜遅くまでお疲れさまでした。
GASの特殊仕様についてググって直ぐに対応してるところとか、腕を上げたな～と感じました😀
それがしはLGTM🍡！

2023-10-05 03:32 UTC, ma-miyagawa commented on index.html
> -
@Itopan1108 

`no newline at end of file` の警告は、３－１の時の分でした。こちらの勘違いで申し訳ございません。
ボタンの名称の修正ありがとうございました。
あとは横山さんがLGTMを出したらマージをお願いします。

2023-10-05 11:41 UTC, h-yokoyama-eiwa reviewed
@Itopan1108 
追加でコメントしました。
インデント揃えたらマージしちゃっていいです。

2023-10-05 11:41 UTC, h-yokoyama-eiwa commented on index.html
> +           </v-card-actions>
インデントが全体で揃っていないですね。
半角SPACE１つ分のところと2つ分のところがある？
揃えた方がいいですよ。

2023-10-05 12:43 UTC, Itopan1108 commented on index.html
> +           </v-card-actions>
@h-yokoyama-eiwa 
ほんとですな。。はしたない。。
今直したので、アップして、それではマージさせてもらいますね！

2023-10-05 12:49 UTC, Itopan1108 commented
それではマージいたします。

2023-10-05 12:49 UTC, merged